### ISSUE TITLE
Hebrew p5.js

### ISSUE THREAD

**Issue by Hbentzur** [Open-Source-Studio-at-ITP/Final-Projects#10]
It doesn't have to be Hebrew!
The thought of teaching young learners programming without having to know English makes me excited. Maybe we can think about it together.

**Comment by shiffman** [comment]
Related to #8!

**Comment by Hbentzur** [comment]
Ooo I missed that.

It is Related – though I'm trying to think how can we even lower the barrier of entry by writing code using the local alphabet. I've seen some examples which looks a bit underwhelming – @shiffman are you familiar with good ones?

🌈

**Comment by shiffman** [comment]
Oh, yes, this is indeed a wonderful idea to explore! [قلب](http://nas.sr/%D9%82%D9%84%D8%A8/) by @nasser is an excellent reference / source of inspiration!

**Comment by guillemontecinos** [comment]
This is an amazing idea, and it's also so related with what we've been working with @codedescuela and @montoyamoraga the last two years. 
Please feel free to ask anything about our experience on that, it'd be a pleasure to help you on it.

**Comment by montoyamoraga** [comment]
@Hbentzur hi! yes, happy to help, right now they are developing the p5.js website in Chinese and there is also an unofficial one in Japanese.

**Comment by nasser** [comment]
More than happy to help however I can :v:

**Comment by Hbentzur** [comment]
@nasser I was just about to email you!
I met with @montoyamoraga, and he mentioned your name with great appreciation. I'm thinking about creative coding workshops in both Hebrew & Arabic in Jerusalem, where I'm from. I know there is still a lot to be done before such a thing would be possible – I'll take it one step at a time.

@nasser, perhaps we can meet next week? the coffee is on me ☝🏼

**Comment by nasser** [comment]
@Hbentzur shoot me an email and lets plan something!
