### ISSUE TITLE
Kinectron, but with realSense

### ISSUE THREAD

**Issue by js6450** [Open-Source-Studio-at-ITP/Final-Projects#11]
I am already sort of involved / working on this, but for my final project, I was thinking of either 1) continuing / refining development of [Kinectron](https://github.com/kinectron/kinectron) created by Lisa Jamhoury who was a resident here last year or 2) creating a realSense version of Kinectron. I think I would end up doing both things in the long run, but for the scope of this class, I would pick one or the other. 

Reason for pursuing the first option: 
* Kinectron uses peer.js, which hadn't been maintained for the last 3 years and recently has gone back into development. I am wondering if there are things we can make use of from the recently added features. I had modified Kinectron to use websockets instead, which also has been working quite well for me, and I want to see if providing users with both options might be the better thing to do. Also, a local version that I have been developing uses terminal / node interface rather than the Electron interface, which is also another thing I would like to actually integrate to the Kinectron itself.

Reason for pursuing the second option:
* Kinect is being discontinued. RealSense is more light weight. I am wondering if we can do a similar thing, but by using RealSense. This might take more time / require more commitment, seeing as this is a more "fresh" project, but I think it will be worth the time and be fun!

If anyone wants to join me on either of the pursuits, please let me know!

**Comment by lunaog** [comment]
This reminds me of this project! Embodied take on the Kinect. Have you seen? She's in the ITP community! 

http://nancynowacek.com/actioncoding

**Comment by shiffman** [comment]
I know that @lisajamhoury would be excited to hear about this so tagging her! Looking into [PoseNet](https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5) (post by @oveddan) could also be an interested option!

**Comment by lisajamhoury** [comment]
@shiffman thanks for the tag. Great to see this idea here!

@js6450 So happy to hear you are thinking of taking this on for your Open Source Studio project! 

Something to consider: 

It would be awesome to do 1 (some modernizing of Ktron code) as a lead into 2 (extending to Real Sense) and then eventually think about how it could be extended to other inputs — like to PoseNet, for example. 

The idea would be to de-couple Kinectron from the Kinect so that it can be used with Real Sense and also Open Pose (and other devices when appropriate). This would be a great resource for people wanting to work with body / depth data online. This approach could also help to create a common language between the different input options through both the documentation and API. This work would tie very nicely into the [xStory](https://www.itpxstory.com/) project (which I recently emailed you about).

**Comment by js6450** [comment]
@lisajamhoury Thank you so much for your feedback! 

Yes, attempting at creating a common language amongst all devices for body / depth via Kinectron would be amazing.

Thank you also for your email about xStory and I'm definitely planning on applying. I think in terms of scoping for open studios final, its sounds like picking the first option might be the best, so I can ease into the second option with, perhaps, xStory (or maybe start some for the open studio project final as well, given that there is time!).

**Comment by D31F43** [comment]
@js6450 I think the project is very interesting. Related to the unmaintained `peer.js`, I think it can be replaced by lots of other projects. Like `Socket.IO`, `JWT`.

**Comment by shiffman** [comment]
@lisajamhoury Are you available to act as a project mentor? I have opened #37 with a draft of guidelines for project mentorship, feedback and thoughts would be welcome.

**Comment by lisajamhoury** [comment]
@shiffman Yes, very excited to be a mentor for the class. @js6450 and I met yesterday about different project and started talking about what her first steps could be for this final. 

The draft looks good. Three meetings in the timeframe is very doable. In our first meeting Jiwon and I will discuss how to best arrange a weekly checkin.

Please lmk what time Dec 11 presentations will be so I can get them on my calendar.

**Comment by shiffman** [comment]
The class meets 12:10 - 2:40pm.. I am still working on the presentation schedule.. we may do it over more than one class, will keep you posted!

**Comment by js6450** [comment]
@lisajamhoury Here is my proposal: https://github.com/js6450/body2web/blob/master/README.md

(the name of the project / application is definitely probably temporary)

**Comment by shiffman** [comment]
Proposal is all set and mentor is assigned!
