### ISSUE TITLE
WIP: Final Project Ideas

### ISSUE THREAD

**Issue by vince19972** [Open-Source-Studio-at-ITP/Final-Projects#13]
## Contribution

- ### p5.js: Programming Concepts Visualization
From some recent discussions with classmates, I find that many programming concepts are too abstract for beginners to comprehend. Most of them are doing assignments without truly understanding of the concepts but only replicating the shallow pattern/form from example codes. With such a great visualization power, I think we could design a series of interactive tutorials that visualize concepts relating to array, objects or class. Ideally, I suppose visualization could help people understand certain concepts faster.

This is probably related to [processing/p5.js#2865](https://github.com/processing/p5.js/issues/2865).

- ### ml5: Looking for collaboration
I know nothing about machine learning and ml5, but interested in learning it. So I'm open to possible rookie collaboration opportunity to contribute to the library.

## New Project

- ### Front-end Developer (or more?) Job Skills Requirements Collection
Everybody knows that front-end development is a new and constantly changing market. It's easy to fall into the struggles of choosing the right learning path between various ones. I suppose it'd be helpful if there's a site, which helps developer make decision easier, that counts the total requirement amount of each skills in all job openings, and ranks the skills according to the counts.

**Comment by shiffman** [comment]
Hi @vince19972 I didn't make this at all clear, but best to file each idea as a separate issue and title it accordingly. The idea is for issues to be individual threads by topic rather than by person. Would you mind closing and re-filing?

**Comment by vince19972** [comment]
@shiffman I just opened issues #16 and #17!
