### ISSUE TITLE
Contributing to organizer.network

### ISSUE THREAD

**Issue by marcelmouse** [Open-Source-Studio-at-ITP/Final-Projects#14]
Hopefully to code but perhaps to more high level things! TBD.

**Comment by nicolaspe** [comment]
I'm also really interested in this!

**Comment by vince19972** [comment]
I'm also interested, but having no specific goal right now.

**Comment by shiffman** [comment]
Are there any pressing issues or features you might suggest @dphiffer as a starting point?

**Comment by dphiffer** [comment]
Good question! I think the most helpful thing right now would be to try it out and to file issues about things that seem awkward or broken. It's very much wet paint, but I think starting to get feedback will help it get traction later on. Here is an invite link for an ITP group I just set up:
https://organizer.network/join/ykt6a8p7by0fipfb

**Comment by dphiffer** [comment]
Link to the "new issue" page:
https://github.com/organizer-network/organizer.network/issues/new

**Comment by shiffman** [comment]
@dphiffer Are you available to act as a project mentor? I have opened #37 with a draft of guidelines for project mentorship, feedback and thoughts would be welcome.

**Comment by dphiffer** [comment]
Yes, I'd be happy to, @shiffman!

**Comment by shiffman** [comment]
Proposal is all set and mentor is assigned!
