### ISSUE TITLE
Final Project Ideas

### ISSUE THREAD

**Issue by linzhangcs** [Open-Source-Studio-at-ITP/Final-Projects#15]
For my final project I have two ideas:

1. Unity Library for [Dialogflow](https://dialogflow.com/) -  Dialogflow had a [library](https://assetstore.unity.com/packages/tools/integration/api-ai-unity-sdk-31498) for unity but the Dialogflow team has stopped supporting it. I want to explore different ways of integrating machine learning into AR/VR in Unity.  This project would help me dive deeper into that topic. 

2. An issue of digital zine  - inspired by [Adjacent](https://itp.nyu.edu/adjacent/issue-3/) and NYT interactive issues, like [#thisis18](https://www.nytimes.com/interactive/2018/10/11/style/this-is-18.html). I am interested in exploring UI design and layout that would translate the look and feel of traditional zine into online spaces.

**Comment by shiffman** [comment]
Hi @linzhangcs! Great ideas! I didn't make this at all clear, but best to file each idea as a separate issue and title it accordingly. The idea is for issues to be individual threads by topic rather than by person. Would you mind closing and re-filing?

**Comment by linzhangcs** [comment]
Moved to #24 and #25
