### ISSUE TITLE
Medical jargon parser

### ISSUE THREAD

**Issue by camilleweins** [Open-Source-Studio-at-ITP/Final-Projects#18]
I want to make Latin and Greek parser for medical abstracts that are in public domain. I want people to be able to not rely on using sources such as Wired or IFLS on Facebook as a way to discover new news related to health. That's the equivalent of reading only the headline for an article or relying on Twitter. Maybe this could be used as a way to make a dataset for an ml5 model?

**Comment by shiffman** [comment]
Can you be more specific about what you mean by Latin and Greek "parser"? Is the idea to "translate" what is found in medical journals into something that lay people could understand? And automate this process? 

I wonder if there's a first step to this project which would just involve manual curation of content in an open source way?

**Comment by shiffman** [comment]
@camilleweins Am I correct that this issue is the correct one associated with the idea you presented today?

**Comment by camilleweins** [comment]
@shiffman Yup!

**Comment by shiffman** [comment]
@sslover will be the mentor for this project!
