### ISSUE TITLE
Educational Game

### ISSUE THREAD

**Issue by camilleweins** [Open-Source-Studio-at-ITP/Final-Projects#19]
Developing a game as supplementary tool for chemistry. It would be interesting if it became a collection of different little 'games' from a bunch of people who have their own metaphors and analogies they use to understand chemistry. Or people could expand the metaphor. Maybe it could be open to different subjects eventually.

**Comment by vince19972** [comment]
It's like a super helpful learning platform for student like me who always fails chemistry!!

**Comment by shiffman** [comment]
One way to think about this project could be to start with a very simple game that you create, open source and document how you made it, and provide a guide for how people can build their own on top of it?
