### ISSUE TITLE
open source open source 

### ISSUE THREAD

**Issue by marcelmouse** [Open-Source-Studio-at-ITP/Final-Projects#2]
I have an idea for a project and wanted to share it here in case anyone wants to collaborate or has feedback. Essentially the project will use GitHub and CircleCi's built in features to create a structure for alternative open source systems (i.e. not code repositories) in order to challenge what can be open source and what open source can look like. i create a repository for it and talked to myself in an issue here: https://github.com/doodybrains/open-open-source/issues/1

**Comment by marcelmouse** [comment]
keeping this idea in the backlog and planning on contributing to dan phiffer's organizer.network! not sure what exactly i will contribute but will update here when i know

**Comment by shiffman** [comment]
Great! @doodybrains you can create a new issue for an idea for organizer.network! I think it makes more sense for each issue to be about a project idea rather than by person.
