### ISSUE TITLE
Runway ML - Final Project

### ISSUE THREAD

**Issue by guillemontecinos** [Open-Source-Studio-at-ITP/Final-Projects#22]
As ml5.js, [Runway's examples](https://github.com/runwayml) are very well documented for coders, but I think they are little hidden for non coders. I'd like to collaborate with this project by developing learning material or a detailed tutorial -written or video- more accessible for users that don't use to code.

**Comment by muji786** [comment]
I think its a great idea. My struggle with alot of libraries and software has not been with the code, but with the actual documentation. You'd be surprised how much OSS code becomes unusable because of lack of docs. Kudos

**Comment by guillemontecinos** [comment]
I talked to @cvalenzuela about developing a @runwayml plugin for Ableton Live with its respective documentation and tutorials. This is really interesting to me because I use Ableton for any musical work I develop.
