### ISSUE TITLE
Processing Foundation (GSoC) - Final Project

### ISSUE THREAD

**Issue by guillemontecinos** [Open-Source-Studio-at-ITP/Final-Projects#23]
I'm a devote of p5.js and the Processing Foundation and have collaborated for a year and a half developing academic material to p5.js beginners in Spanish. I've also applied twice to the Fellowship call without success. I'm opened to collaborate in any need of the project p5.js or the Foundation itself.

**Comment by shiffman** [comment]
Are there aspects of the p5.js Spanish language materials that need attention / improvements / work that would be suitable as a final project here? Also, would writing a guide about making a p5.js translation for other languages be helpful for the future? cc @lmccart

**Comment by lmccart** [comment]
Hi @guillemontecinos, yes! Both of these are huge needs. In terms of translation, there is an automatically-generated list [here](https://github.com/processing/p5.js-website/blob/master/i18n-tracking.yml) but I don't think it's complete. I think the best thing to do would be to go through the spanish version of the site and look for places there's still english. And a guide for others wanting to contribute in this way would be very helpful.

**Comment by guillemontecinos** [comment]
Hi @lmccart thanks for the answer and sorry for the delay! I agree that a guide for translating the p5 website and examples can be very useful and I'd like to work on it as my project for this class. 
Do you or @montoyamoraga have references or material that could be useful to design the translation guide?

**Comment by lmccart** [comment]
I think most of the info is here: https://github.com/processing/p5.js-website#internationalization-i18n-and-structure, but this could be broken out into it's own page, structured more clearly, and accompanied with more explanation. You might realize other pieces of information that are missing as you're going through it.

There's also [this file](https://github.com/processing/p5.js-website/blob/master/i18n-tracking.yml) that is doing some auto-tracking, but I'm not sure if it's well documented how to use this file and where to find it. cc @limzykenneth

**Comment by limzykenneth** [comment]
@guillemontecinos For the purpose of tracking untranslated pages (excluding documentation and examples) you can directly add to [this file](https://github.com/processing/p5.js-website/blob/master/i18n-tracking.yml) (hopefully the yml structure makes sense). After you have translated those untranslated entries you can go ahead and remove the relevant entries, following instructions [here](https://github.com/processing/p5.js-website/wiki/Tracking-Translations#for-contributors-working-on-translations).

It's not a super elegant system so it is also up for improvement as well.

For examples and documentation, there is currently no way of tracking translation progress so you will need to go through them manually to find untranslated ones. A system to help track these translations will also be a great addition overall.

If you have questions regarding the translation tracking setup just ping me.

**Comment by lmccart** [comment]
oh there it is, thanks @limzykenneth.
@guillemontecinos there are a few other pages in the wiki that would be useful to link to or include info from: https://github.com/processing/p5.js-website/wiki

**Comment by guillemontecinos** [comment]
Thanks @lmccart & @limzykenneth for all that info!

**Comment by shiffman** [comment]
I just created #37 with a set of draft guidelines for final project mentorship. @lmccart @limzykenneth I'd love any thoughts or feedback on the guidelines and let me know if either of you have availability or interest in participating!

**Comment by limzykenneth** [comment]
@shiffman I have some but limited availability but I am interested in participating so depending on what is expected of the role I should be able to help with guiding students interested in translation or other certain aspects of the p5.js project.

**Comment by lmccart** [comment]
Hi @shiffman this is great! I think I can't commit to being a mentor this semester, but can be generally available via email/github for any p5.js related project (or any projects that may overlap with my skills) to answer questions and help guide students toward useful resources.

**Comment by guillemontecinos** [comment]
I think @montoyamoraga can also be a mentor for this project. What do you think @shiffman @lmccart @limzykenneth ?

**Comment by shiffman** [comment]
Yes, if @montoyamoraga is interested that would be terrific! Here are the guidelines and expectations (open to discussion of course):

https://github.com/Open-Source-Studio-at-ITP/Final-Projects/blob/source/mentor-guidelines.md

**Comment by montoyamoraga** [comment]
Hi @shiffman @guillemontecinos 
 I read the guidelines and this is great, thanks for the invite, I accept to be a mentor! =)

**Comment by shiffman** [comment]
Proposal is all set and mentor is assigned!
