### ISSUE TITLE
Unity Library for Dialogflow 

### ISSUE THREAD

**Issue by linzhangcs** [Open-Source-Studio-at-ITP/Final-Projects#24]
[Dialogflow](https://dialogflow.com/) had a [library](https://assetstore.unity.com/packages/tools/integration/api-ai-unity-sdk-31498) for unity but the Dialogflow team has stopped supporting it. I want to explore different ways of integrating machine learning into AR/VR in Unity.  This project would help me dive deeper into that topic.

**Comment by tinkrmind** [comment]
I love the idea of using Dialogflow in VR! Especially if Dialogflow is connected to some speech to text API it makes a lot of sense as a controller while in VR.

**Comment by shiffman** [comment]
Great idea! Would this require buy-in from the maintainers of Dialogueflow? Or can this be done independently as an "extension" / "plug-in"? What kind of resources / help would you need? More from the unity side or the dialogueflow side? Or both?

**Comment by ilanabonder** [comment]
@linzhangcs I would love to help!!! I've been really interested on integrating dialogflow in Unity for AR projects --- would you like to work on that together or are you thinking more on doing a solo project? I haven't decided my project yet and would be very excited to work with you on that :)

**Comment by alicehgsun** [comment]
@linzhangcs I also find this interesting, especially after taking Nicole's [Unconventional Uses of Voice Technology class](https://experiments.withgoogle.com/mystery-animal) and hearing her comment about how using dialogflow in Unity used to be much simpler(?). Reaching out to her might be helpful!

**Comment by linzhangcs** [comment]
> Great idea! Would this require buy-in from the maintainers of Dialogueflow? Or can this be done independently as an "extension" / "plug-in"? What kind of resources / help would you need? More from the unity side or the dialogueflow side? Or both?

This would be done as an unity plugin. It seems Dialogflow API will be closed in a year or so, I need to find an alternative API for NLP intent recognition. I'd love to find a mentor who have experience with Unity scripting.

**Comment by linzhangcs** [comment]
> @linzhangcs I would love to help!!! I've been really interested on integrating dialogflow in Unity for AR projects --- would you like to work on that together or are you thinking more on doing a solo project? I haven't decided my project yet and would be very excited to work with you on that :)

I'd love to work on this project together! :)

**Comment by alicehgsun** [comment]
Here're in-class example by Aidan and past project from Nicole, using unity + dialogflow:
- [Garden Friends](https://experiments.withgoogle.com/garden-friends)
- [Paradise Blues](https://www.aidanjnelson.com/blog/hello-computer/paradise-blues/)

**Comment by shiffman** [comment]
A reminder to add your proposal to:
https://github.com/Open-Source-Studio-at-ITP/Final-Projects/blob/source/proposals.md

**Comment by alicehgsun** [comment]
The link is added via [pull request](https://github.com/Open-Source-Studio-at-ITP/Final-Projects/pull/51)!

**Comment by shiffman** [comment]
This project is all set to go!
