### ISSUE TITLE
 Digital Zine

### ISSUE THREAD

**Issue by linzhangcs** [Open-Source-Studio-at-ITP/Final-Projects#25]
For this idea, I want to make an issue of digital zine - inspired by  [Adjacent](https://itp.nyu.edu/adjacent/issue-3/) and NYT interactive issues, like [#thisis18](https://www.nytimes.com/interactive/2018/10/11/style/this-is-18.html). I am interested in exploring UI design and layout that would translate the look and feel of traditional zines into online digital zines.

**Comment by tinkrmind** [comment]
It'll be interesting if you can spell out the framework for starting a digital zine. I'm imagining Wordpress for digital zines.. 🤔

**Comment by shiffman** [comment]
Do you have an idea for a topic that the zine would focus on? What does "open sourcing" a zine add to the making of it, would contributions to the content be open?
