### ISSUE TITLE
openframeworks book

### ISSUE THREAD

**Issue by nicolaspe** [Open-Source-Studio-at-ITP/Final-Projects#26]
For another class I have been learning openframeworks, mainly using the book for the basics and shader chapters. Sadly, many examples are missing key information and/or are vastly different from the example files provided. I would clean, correct and provide more information for this to be a better educational resource.

**Comment by camilleweins** [comment]
I've been learning openframeworks too and think this is a great idea. I think it would be interesting to do something in this style: https://aryaboudaie.com/java/python/technical/educational/2017/11/13/python-for-java-programmers.html

**Comment by shiffman** [comment]
Are you referring to this book? https://github.com/openframeworks/ofBook/

There is also a call for things that need attention on the learning page. https://github.com/openframeworks/ofBook/

This would fit into the framework of a final project for this class very nicely.
