### ISSUE TITLE
Idea: P5.JS Gif/Animation Library

### ISSUE THREAD

**Issue by WenheLI** [Open-Source-Studio-at-ITP/Final-Projects#27]
This is an idea of introducing a Gif processing Library into P5.JS since gif is commonly used and sometimes help with the performance.  From my experience, if we can build up a Gif library we may introduce a lower computation consuming way of animation. This idea is still a rough thing, is anyone have some suggestions on that? I may attach a detailed description later on this issue.

**Comment by js6450** [comment]
I've used this javascript library called [gif.js](https://jnordberg.github.io/gif.js/) in combination with p5 before. Maybe a good resource to take a look and see how they are generating gifs in javascript.

**Comment by tinkrmind** [comment]
It'll be great to also provide direct API links to gif sources like giphy or gifs.com. I can imagine all sorts of hillarity emerging for this project. I predict an arduino controlled cat gif showing project within the first two days of you making this available!

**Comment by shiffman** [comment]
GIFs can be natively loaded and displayed using `createImg()` in p5. However, there is no way (as far as I know) to use `loadImage()` with a GIF and unpack the frames for drawing in canvas. Is this what you are proposing to do?

ITP alum and former resident @craigson worked on a library to generate GIFs from a p5 sketch a while back. See: https://github.com/Craigson/p5Gif

**Comment by lmccart** [comment]
also there's this outdated one from another ITP alum @antiboredom https://github.com/antiboredom/p5.gif.js/tree/master

**Comment by WenheLI** [comment]
I am thinking of developing such a library that can generate, unpack and manipulate the gif rather than simply loading it. I will look into these resources! I am sure they will be super useful.

**Comment by shiffman** [comment]
Noting a link to the proposal is merged in #39.

https://github.com/WenheLI/p5.gif/blob/master/README.md    (Updated on Nov 10)

**Comment by shiffman** [comment]
Mentor will be @antiboredom!
