### ISSUE TITLE
Blender Quick Hacks

### ISSUE THREAD

**Issue by jameshosken** [Open-Source-Studio-at-ITP/Final-Projects#28]
There are 16 open and approved New Feature issues tagged as "Beginner Friendly" on the Blender project. Although there are many ways to contribute to Blender, these 'Quick Hacks' are promoted as the easiest and most fulfilling way to get started.

[Quick Hacks page](https://developer.blender.org/project/view/34/)

**Comment by shiffman** [comment]
Looking at this list it's nicely documented for beginners and first-timers. I wonder what would I need to know to jump in? Is there a getting started contributing guide? What sort of development environment? Is it C++?
