### ISSUE TITLE
Diasporadical Radio First Inkling 

### ISSUE THREAD

**Issue by lunaog** [Open-Source-Studio-at-ITP/Final-Projects#3]
Last year I worked on a project for the Impossible Maps class. The map is based off an app I use which allows the user to click on a country and decade era and hear music from that time / place. The issue I have with this map is that It seems to be curated by a very select group of French people who while have good taste, have very limited knowledge of music outside of certain countries. My idea is to focus in the theme of the map as to be a map of “independent global artists” (artists not backed by Sony, Universal or Columbia and with a focus on people of the global south, indigenous and Black people. I also want to “open source” this map and develop it so that there is a node component which allows user-generated content. 

I’ve been struggling as to whether this counts as “open source” because there would still be a curator (me), but I’m realizing that in all open source projects there is a curator, whether it is a Benevolent dictator or group of people. Part of my design process recently has been to trust my taste so I think that asking for contributions and leaning more on “accept” than not accept will be what I do. 

My next steps for this project is to clean it up, probably re-do the node component and migrate to Github. I would like to send out to other taste-makers, artists, art practitioners to begin filling it out more. My dream to finish this project would be to distort the map in that it magnified the areas in which there were more musical contributions and to create a user-interface that was very friendly but went somehow through GitHub to track contributions.

**Comment by lunaog** [comment]
This is my idea for my final project! I welcome suggestions or critique or let me know if you want to collaborate!

**Comment by marcelmouse** [comment]
i think this is a great idea ! 

super curious to see what the code looks like _and_ what the visuals look like !

will the project be hosted in a single place? i wonder if there could be collaborative layers to the map...for example you would control the most bottom layer...another user could submit a pull request for a new layer which other users can toggle on and off....this way its essentially curated by you but also a living document of different kinds of maps for different kinds of music

reminded of this: http://radio.garden

**Comment by shiffman** [comment]
@lunaog This issue looks like the right one to tie to your final project, yes? Would you mind renaming the title of the issue (see "edit" button near "new issue" button at top of page) to something more specific?

**Comment by lunaog** [comment]
Should I still close it tho? I dont think its relevant anymore !

**Comment by shiffman** [comment]
I am trying to decide what makes the most sense. I think, yes, if a project has a proposal submitted (and "accepted") as well as a mentor assigned, then the proposal issue can be closed! Removing the "needs mentor" label and closing! 🎉
