### ISSUE TITLE
Arduino Help Wanted

### ISSUE THREAD

**Issue by jameshosken** [Open-Source-Studio-at-ITP/Final-Projects#30]
The Arduino project has a "[Help Wanted](https://github.com/arduino/Arduino/issues?q=is%3Aissue+is%3Aopen+label%3A%22Help+wanted%22)" section on its GitHub issues page. These issues are said to be a good place for beginners to get involved. A final project could perhaps tackle one of these open issues.

Note: the issues are not all code/hardware related. As of now the second top issue is about creating [better licensing documentation](https://github.com/arduino/Arduino/issues/6590)

**Comment by tinkrmind** [comment]
You'll get mad street cred for contributing to Arduino in any way! I'm kinda surprised more ITP students aren't contributing to Arduino. Do you envision working on multiple small projects or tackling a chunky issue?

**Comment by D31F43** [comment]
I think most of these tasks are not easy to deal with. They are a bit challenging, but interesting. And I find another project related - [Arduino Create](https://github.com/arduino/arduino-create-agent/issues). It is also an official project, but brings native to cloud.
