### ISSUE TITLE
Programmable-Air - Developing a community - Final Project

### ISSUE THREAD

**Issue by tinkrmind** [Open-Source-Studio-at-ITP/Final-Projects#31]
[Programmable-Air](programmable-air.com) is a hardware tool and accompanying software that allows anyone familiar with Arduino to experiment with low power pneumatics. I want to develop a community of users around Programmable-Air. A place where users can not only learn from my documentation but share their success and failure stories, modifications, and discuss project ideas. A forum, essentially..

There are many places for people to grather and discuss projects in electronics and pneumatics. The one that comes closest to this project is the [Harvard Soft Robotics](https://softroboticstoolkit.com/forum). But it leaves a lot wanting. 

By the end of the semester I wish to have the following things happen:
* Active discussion about a Programmable-Air project on an online platform
* Having a user develop and share their work activated by Programmable-Air
* Having a user modify their Programmable-Air hardware and share their mods, and having another user replicate it

The first step is to make an online repo and getting started documentation where someone interested in using Programmable-Air can learn how to do so. The next step is to make an online form where people can self organize and share work. This could be a website I build or an existing forum or sub Reddit or similar. I shall evaluate the choices based on scalability, modifiability, ease of use for users, accessibility etc. Finally, I have to manufacture Programmable-Air beta units and deliver them to users excited to use it.

**Comment by shiffman** [comment]
In terms of forum software, as a reference, we use discourse for the Processing Foundation.

https://discourse.processing.org/
https://www.discourse.org/

A lightweight way of having people share their work could be a good way to start. Building an entire new content management system might be too much for this semester. 

If your users are comfortable with GitHub even just editing a markdown / yaml page could work. This is what I do for The Coding Train with Github pages:

https://github.com/CodingTrain/website/wiki/Community-Contributions-Guide

If GitHub is not viable, then even a google form and a webpage that pulls the data (easy to do this from node or even client-side JS) could be a great way to get started and have a prototype up fast.

All of your ambitions and ideas are great and in the spirit of this class and important elements for your project. You might find it helpful to focus your scope for this final project, even getting a nicely organized repository with good documentation is a big project.

**Comment by shiffman** [comment]
@tinkrmind Are you able to present this project idea in class next week?

**Comment by shiffman** [comment]
Also, a reminder to add your proposal to:
https://github.com/Open-Source-Studio-at-ITP/Final-Projects/blob/source/proposals.md

**Comment by tinkrmind** [comment]
Sorry for the late response! Yes, I will be ready to present the idea in the next class. I'll add the proposal ASAP.

**Comment by shiffman** [comment]
This project is all set now with #54
