### ISSUE TITLE
BODIES OF KNOWLEDGE- Idea

### ISSUE THREAD

**Issue by lunaog** [Open-Source-Studio-at-ITP/Final-Projects#33]
Would be amazing for someone to get involved with this project: 

https://github.com/sparcopen/doathon/issues/20

BODIES OF KNOWLEDGE* aim to demonstrate how underrepresented groups such as women* trans* and/or people of colour can take a much broader scope in the development chain, from design to manufacturing and the mainstream adoption of technologies.

**Comment by shiffman** [comment]
This looks like a wonderful initiative. Glancing over it quickly, it looks like the doathon was last year (Oct/Nov 2017). Is there a plan for another and/or an active area of the project that could use a contribution?

**Comment by lunaog** [comment]
Yes there is another one this year coming up soon! I am not sure how to find it on their Github but it's here: 
https://doathon.opencon2018.org/
