### ISSUE TITLE
Final Project Idea about embedding p5.js in VSCode

### ISSUE THREAD

**Issue by D31F43** [Open-Source-Studio-at-ITP/Final-Projects#4]
Visual Studio Code is known as a light, pretty and powerful code editor which is extendable and open-sourced. Our (with @WenheLI) idea is to make VSCode a friendly workspace for p5.js (which is also another open source project) by building a language server for p5.js APIs and a quick instant viewer for what you've done with the code you are working on.

With the help the language server, users can get rid of remembering most structures of code or built-in methods but only focus on how to make it a better art piece. As for the instant viewer, it renders a new screen as soon as the code changes, which saves users' time.

**Comment by shiffman** [comment]
I found a few existing extensions that might serve as good resources / references.

https://marketplace.visualstudio.com/items?itemName=filipesabella.live-p5
https://marketplace.visualstudio.com/items?itemName=garrit.p5canvas
https://marketplace.visualstudio.com/items?itemName=acidic9.p5js-snippets

I'm not sure if any of these are actively being maintained. Or if they use a language server.

**Comment by D31F43** [comment]
@shiffman Thanks, and we opened a early todo here. And find some information provided by VSCode and some other similar projects.

https://github.com/VSCode-Processing/P5LanguageServer/issues/1

**Comment by vince19972** [comment]
This is cool. Please keep sharing your progress on this, I'd really like to know how to build an extension or using language server!
