### ISSUE TITLE
Blenduino

### ISSUE THREAD

**Issue by jameshosken** [Open-Source-Studio-at-ITP/Final-Projects#40]
Getting data from Arduino to Blender (and back?), easily.

[Proposal](https://github.com/jameshosken/Blenduino)

TL;DR: Create a Blender addon to simply capture incoming serial data (e.g. from an Arduino) and process it in a way that's useful to modelers, animators, interaction designers, etc in a virtual 3D environment.

**Comment by jameshosken** [comment]
@michaelshiloh has agreed to be the mentor for this project!

**Comment by shiffman** [comment]
Wonderful, closing this issue, new ones related to this project can be filed as necessary!
