### ISSUE TITLE
Final Project Ideas - work in progress

### ISSUE THREAD

**Issue by guillemontecinos** [Open-Source-Studio-at-ITP/Final-Projects#5]
Original File can be found [here](https://github.com/guillemontecinos/itp_fall_2018_open_source_studio/blob/master/week_7/project_ideas.md).

## Processing Foundation - GSoC
I'm a devote of p5.js and the Processing Foundation and have collaborated for a year and a half developing academic material to p5.js beginners in Spanish. I've also applied twice to the Fellowship call without success. I'm opened to collaborate in any need of the project p5.js or the Foundation itself.

### Pre-trained models
Some pre-trained models for style transfer -as *Matilde Pérez* and *Matta*- are not as accurate as expected. I'd like to improve them by checking the dataset built for training the model and correcting if needed. I'd like to train other models if there are any on demand.

### Learning material
I've realized that ml5.js learning material is pretty well documented. Apart from that there are tutorials in The Coding Train.
Despite, there are many things to do in order to make ML more accessible. I'd like to develop an intro tutorial more detailed, maybe as a proto-tiny-guide, inspired in the intro to p5.js book. If not, there is material still in a development stage, as the [pix2pix tutorial](https://ml5js.org/docs/pix2pix-example) that could be addressed.

### Code
I don't know if coding improves are needed in the project -probably there are- but I'd like to collaborate in them.

## Wekinator
Wekinator as a ML tool for creative purposes -mainly for live performances- is very useful and challenging. The problem of Wekinator is its the [documentation](http://www.wekinator.org/detailed-instructions/) is not friendly. I guess it's due project is that was created and has been maintained for only one person -despite it's stated as an open-source project.

I'd like to collaborate by creating a more detailed documentation or a set of tutorials that could help beginners to start using Wekinator.

## Runway ML
As ml5.js, [Runway's examples](https://github.com/runwayml) are very well documented for coders, but I think they are little hidden for non coders. I'd like to collaborate with this project by developing learning material or a detailed tutorial -written or video- more accessible for users that don't use to code.

**Comment by marcelmouse** [comment]
I like the idea of a proto-tiny-guide for ML5 ! 

I agree that the project is extremely well documented and the tutorials are easy to follow but there could be something more! 

Wondering what exactly would be in this guide?

I think more information on how to use ML5 in general! Maybe speculations on what ML5 could be used for in a personal project. Or clarifying what is the bare minimum someone needs to get up and running with ML5? What are some "real world" examples for ML5 in use?

**Comment by shiffman** [comment]
Hi @guillemontecinos! Great ideas! I didn't make this at all clear, but best to file each idea as a separate issue and title it accordingly. The idea is for issues to be individual threads by topic rather than by person. Would you mind closing and re-filing? (And @doodybrains might have to repost the comment, sorry!)

**Comment by guillemontecinos** [comment]
Sure!

**Comment by guillemontecinos** [comment]
Moved to here https://github.com/Open-Source-Studio-at-ITP/Final-Projects/issues/20
