### ISSUE TITLE
Create Final Presentation Schedule

### ISSUE THREAD

**Issue by shiffman** [Open-Source-Studio-at-ITP/Final-Projects#57]
Starting point #56

* [x] p5.gif.js
* [x] Blenduino
* [x] p5.js translation
* [x] Statable
* [x] Lexicon
* [x] Diasporadical Radio
* [x] Organizer.network
* [x] Dialogflow V2: Unity Plugin
* [x] Programmable-Air
* [x] Datavyu
* [x] body2web

**Comment by shiffman** [comment]
Leaving this open until everyone has a slot:

**Comment by js6450** [comment]
@shiffman Link to the final project presentation doc is broken on the readme.md, but I'm confused why it's broken because it looks like it should work for me. Could you take a look?

**Comment by shiffman** [comment]
@js6450 this is fixed now, thanks for the report!

**Comment by shiffman** [comment]
@vince19972 and @tinkrmind You both signed up for 1:20pm. Since @vince19972's pull request was first I put @tinkrmind at 1:40pm. Ok with you both?

**Comment by shiffman** [comment]
The schedule is now complete. @Open-Source-Studio-at-ITP/all-students please check your times and re-open this issue or e-mail me if need be!
