### ISSUE TITLE
p5.js documentation help

### ISSUE THREAD

**Issue by shiffman** [Open-Source-Studio-at-ITP/Final-Projects#7]
If you are interested in contributing to p5 as your final project, this post "documentation help needed!" post is a good place to start.

https://github.com/processing/p5.js/issues/2865

An idea for a tutorial, for example, could be a final project... even translating [a Processing one](https://processing.org/tutorials/) that is not part of the p5 universe yet?

**Comment by lmccart** [comment]
It would also be awesome to have a single page in the [developer_docs](https://github.com/processing/p5.js/tree/master/developer_docs) folder that covered the info from this issue, so it could be easier to find.
