### ISSUE TITLE
p5.js translation

### ISSUE THREAD

**Issue by shiffman** [Open-Source-Studio-at-ITP/Final-Projects#77]
This is an issue for feedback and discussion on final project presentations and documentation. It will be closed after documentation is submitted and the semester has completed.

**Comment by guillemontecinos** [comment]
[Final Documentation](https://github.com/guillemontecinos/itp_fall_2018_open_source_studio/blob/master/final_project/final.md) can be found here.

**Comment by shiffman** [comment]
Great work on this project! It is so wonderful to see the continued discussion and progress of this work as it is folded into the p5.js website and related repos. Being closely involved with the Processing Foundation I know how vital and important this project is. Translating the reference and materials is such time consuming and difficult work. On top of that, maintaining and updating a translation as a project changes over time is so easily forgotten. Having a documented process and guide for translations is a key foundation to the success and expansion of the internationalization of p5.js. You made excellent use of the features of GitHub to document your process along the way and engage with project maintainers and mentors. One question I wonder is whether there might be a separate guide for someone who wants to add to or edit an existing translation vs. create a new one?
