### ISSUE TITLE
p5.js translation edits and additions

### ISSUE THREAD

**Issue by shiffman** [Open-Source-Studio-at-ITP/Final-Projects#8]
Another idea for a final project related to p5.js would be to help with edits or additions to the translations. At the moment there is:

* [p5.js en español](https://p5js.org/es/)
* [p5.js 用普通话](https://p5js.org/zh-Hans/)

More information can be found here:
https://github.com/processing/p5.js-website#internationalization-i18n-and-structure

**Comment by alicehgsun** [comment]
Hi @shiffman, are we looking for some specific languages for translation? If not, I can participate for Korean one!
