### ISSUE TITLE
Diasporadical Radio

### ISSUE THREAD

**Issue by shiffman** [Open-Source-Studio-at-ITP/Final-Projects#80]
This is an issue for feedback and discussion on final project presentations and documentation. It will be closed after documentation is submitted and the semester has completed.

**Comment by shiffman** [comment]
@lunaog is there a link to your final presentation / write-up? I'm looking at: https://github.com/lunaog/radio Thanks!

**Comment by lunaog** [comment]
Yes! My final write-up is here: 
https://wp.nyu.edu/luna/2018/12/11/oss-final-presentation/

**Comment by shiffman** [comment]
Thanks, added in #90 which can close this issue when merged!

Great job this semester on Diasporadical Radio! You worked very hard to solve a variety of difficult technical problems and it was wonderful to see a fully functioning version of the project at your final presentation! The mission and goals of your project were clearly stated and presented well. If you are to continue the project further I think a good next step would be to reach out to communities that might like to participate to expanding the dataset. User testing the interaction around adding new music may reveal missing features or points of confusion. A small thing re: project documentation - I might suggest renaming `How-to.md` to `CONTRIBUTING.md` and `Code-of-ethics` to 'CODE_OF_CONDUCT.md` which is a bit more standard and will be detected by GitHub for featuring (but perhaps you have reasons for your naming?) More importantly, however, a useful next step might be to separate the guide for contributing to the codebase from the one for contributing music. A video walk-through about adding new music would probably be useful for non-technical contributors. I hope you continue this work!

**Comment by shiffman** [comment]
Merged #90 and closing, great work!
