### ISSUE TITLE
Dialogflow V2: Unity Plugin

### ISSUE THREAD

**Issue by shiffman** [Open-Source-Studio-at-ITP/Final-Projects#82]
This is an issue for feedback and discussion on final project presentations and documentation. It will be closed after documentation is submitted and the semester has completed.

**Comment by shiffman** [comment]
Could you please add a link to your final documentation to the [final presentation page](https://github.com/Open-Source-Studio-at-ITP/Final-Projects/blob/source/final-schedule.md)? Thanks!

**Comment by alicehgsun** [comment]
Sorry for late update! I requested via PR

**Comment by shiffman** [comment]
Great work this semester on Dialogflow V2: Unity Plugin! You picked a very challenging project from a technical point of view and I was impressed with how you were able to get everything working. Your presentation about the goals and utility of the plugin was excellent and clear. This project is unique to this class in that while your plug-in is open source, it is designed for DialogFlow and Unity, neither of which are open source. This can make the project difficult to maintain, but also could be an opportunity for funding / support given the corporate backing of both projects. Your documentation is excellent, great job making video walkthroughs of the very complicated process of getting DialogFlow API configured to use within Unity. Two next steps for your work that I might suggest are (1) teach a workshop for ITP students to use the plugin and (2) collect some projects made with the plugin to feature with the documentation. Congrats!
