### ISSUE TITLE
Organizer visual language

### ISSUE THREAD

**Issue by Hbentzur** [Open-Source-Studio-at-ITP/Final-Projects#9]
I spoke to Dan Phiffer about creating a visual language for Organizer –
It can be nice to collaborate with someone in class since the visual language often rises from brainstorming with who is involved in the creative process.

**Comment by shiffman** [comment]
Tagging @dphiffer!

**Comment by Hbentzur** [comment]
Thanks @shiffman ⚡️

**Comment by dphiffer** [comment]
In case it's helpful, here is the photo that I've adapted for the current website. It's on my "mood board," so to speak. https://mltshp.com/p/1EEOG

And the colors I pretty much eyedropped straight from the Firefox Nightly logo: https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly

**Comment by marcelmouse** [comment]
@Hbentzur planning on contributing to organizer.network also : )

**Comment by shiffman** [comment]
I'm closing this issue but leaving #14 open as the thread for the project, if that's not right, let me know!
